TRAVELPLUS/Controllers/Report/LiabilitiesPartnerReportController.cs
using CRM.Core;
using CRM.Infrastructure;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TRAVELPLUS.Models;
using TRAVELPLUS.Utilities;

namespace TRAVELPLUS.Controllers.Report
{
    [Authorize]
    public class LiabilitiesPartnerReportController : BaseController
    {
        // GET: LiabilitiesPartnerReport

        #region Init

        private IGenericRepository<tbl_Dictionary> _dictionaryRepository;
        private IGenericRepository<tbl_ServicesPartner> _servicesPartnerRepository;
        private IGenericRepository<tbl_Tour> _tourRepository;
        private IGenericRepository<tbl_TourOption> _tourOptionRepository;
        private IGenericRepository<tbl_ReviewTour> _reviewTourRepository;
        private IGenericRepository<tbl_ReviewTourDetail> _reviewTourDetailRepository;
        private IGenericRepository<tbl_Customer> _customerRepository;
        private IGenericRepository<tbl_CustomerVisa> _customerVisaRepository;
        private IGenericRepository<tbl_Tags> _tagsRepository;
        private IGenericRepository<tbl_Task> _taskRepository;
        private IGenericRepository<tbl_DocumentFile> _documentFileRepository;
        private IGenericRepository<tbl_AppointmentHistory> _appointmentHistoryRepository;
        private IGenericRepository<tbl_ContactHistory> _contactHistoryRepository;
        private IGenericRepository<tbl_Contract> _contractRepository;
        private IGenericRepository<tbl_Partner> _partnerRepository;
        private IGenericRepository<tbl_TourGuide> _tourGuideRepository;
        private IGenericRepository<tbl_TourSchedule> _tourScheduleRepository;
        private IGenericRepository<tbl_TourCustomer> _tourCustomerRepository;
        private IGenericRepository<tbl_TourCustomerVisa> _tourCustomerVisaRepository;
        private IGenericRepository<tbl_Staff> _staffRepository;
        private IGenericRepository<tbl_LiabilityCustomer> _liabilityCustomerRepository;
        private IGenericRepository<tbl_LiabilityPartner> _liabilityPartnerRepository;
        private IGenericRepository<tbl_CustomerContact> _customerContactRepository;
        private IGenericRepository<tbl_CustomerContactVisa> _customerContactVisaRepository;
        private IGenericRepository<tbl_UpdateHistory> _updateHistoryRepository;
        private DataContext _db;

        public LiabilitiesPartnerReportController(IGenericRepository<tbl_Dictionary> dictionaryRepository,
            IGenericRepository<tbl_ServicesPartner> servicesPartnerRepository,
            IGenericRepository<tbl_Tour> tourRepository,
            IGenericRepository<tbl_TourOption> tourOptionRepository,
            IGenericRepository<tbl_ReviewTour> reviewTourRepository,
            IGenericRepository<tbl_ReviewTourDetail> reviewTourDetailRepository,
            IGenericRepository<tbl_Customer> customerRepository,
            IGenericRepository<tbl_CustomerVisa> customerVisaRepository,
            IGenericRepository<tbl_Tags> tagsRepository,
            IGenericRepository<tbl_Task> taskRepository,
            IGenericRepository<tbl_DocumentFile> documentFileRepository,
            IGenericRepository<tbl_AppointmentHistory> appointmentHistoryRepository,
            IGenericRepository<tbl_ContactHistory> contactHistoryRepository,
            IGenericRepository<tbl_Contract> contractRepository,
            IGenericRepository<tbl_Partner> partnerRepository,
            IGenericRepository<tbl_TourGuide> tourGuideRepository,
            IGenericRepository<tbl_TourSchedule> tourScheduleRepository,
            IGenericRepository<tbl_TourCustomer> tourCustomerRepository,
            IGenericRepository<tbl_TourCustomerVisa> tourCustomerVisaRepository,
            IGenericRepository<tbl_Staff> staffRepository,
            IGenericRepository<tbl_LiabilityCustomer> liabilityCustomerRepository,
            IGenericRepository<tbl_LiabilityPartner> liabilityPartnerRepository,
            IGenericRepository<tbl_CustomerContact> customerContactRepository,
            IGenericRepository<tbl_CustomerContactVisa> customerContactVisaRepository,
            IGenericRepository<tbl_UpdateHistory> updateHistoryRepository,
            IBaseRepository baseRepository)
            : base(baseRepository)
        {
            this._dictionaryRepository = dictionaryRepository;
            this._servicesPartnerRepository = servicesPartnerRepository;
            this._tourRepository = tourRepository;
            this._reviewTourRepository = reviewTourRepository;
            this._reviewTourDetailRepository = reviewTourDetailRepository;
            this._customerRepository = customerRepository;
            this._customerVisaRepository = customerVisaRepository;
            this._tagsRepository = tagsRepository;
            this._taskRepository = taskRepository;
            this._documentFileRepository = documentFileRepository;
            this._appointmentHistoryRepository = appointmentHistoryRepository;
            this._contactHistoryRepository = contactHistoryRepository;
            this._contractRepository = contractRepository;
            this._partnerRepository = partnerRepository;
            this._tourGuideRepository = tourGuideRepository;
            this._tourScheduleRepository = tourScheduleRepository;
            this._tourCustomerRepository = tourCustomerRepository;
            this._tourCustomerVisaRepository = tourCustomerVisaRepository;
            this._tourOptionRepository = tourOptionRepository;
            this._staffRepository = staffRepository;
            this._liabilityCustomerRepository = liabilityCustomerRepository;
            this._liabilityPartnerRepository = liabilityPartnerRepository;
            this._customerContactRepository = customerContactRepository;
            this._customerContactVisaRepository = customerContactVisaRepository;
            this._updateHistoryRepository = updateHistoryRepository;
            _db = new DataContext();
        }
        #endregion

        #region Permission
        int SDBID = 6;
        int maPB = 0, maNKD = 0, maNV = 0, maCN = 0;
        void Permission(int PermissionsId, int formId)
        {
            var list = _db.tbl_ActionData.Where(p => p.FormId == formId && p.PermissionsId == PermissionsId).Select(p => p.FunctionId).ToList();

            var ltAccess = _db.tbl_AccessData.Where(p => p.PermissionId == PermissionsId && p.FormId == formId).Select(p => p.ShowDataById).FirstOrDefault();
            if (ltAccess != 0)
                this.SDBID = ltAccess;

            switch (SDBID)
            {
                case 2: maPB = clsPermission.GetUser().DepartmentID;
                    maCN = clsPermission.GetUser().BranchID;
                    break;
                case 3: maNKD = clsPermission.GetUser().GroupID;
                    maCN = clsPermission.GetUser().BranchID; break;
                case 4: maNV = clsPermission.GetUser().StaffID; break;
                case 5: maCN = clsPermission.GetUser().BranchID; break;
            }
        }
        #endregion

        #region List

        //[CheckSessionTimeOut]
        public ActionResult Index()
        {
            Permission(clsPermission.GetUser().PermissionID, 1118);
            return View();
        }

        [ChildActionOnly]
        public ActionResult _Partial_ListTourReport()
        {
            Permission(clsPermission.GetUser().PermissionID, 1118);

            var model = _liabilityPartnerRepository.GetAllAsQueryable().AsEnumerable()
                .Where(p => p.IsDelete == false
                    && (p.StaffId == maNV | maNV == 0)
                    & (p.tbl_Staff.DepartmentId == maPB | maPB == 0)
                    & (p.tbl_Staff.StaffGroupId == maNKD | maNKD == 0)
                    & (p.tbl_Staff.HeadquarterId == maCN | maCN == 0))
                .Select(p => new LiabilitiesPartnerReportViewModel()
                {
                    Id = p.Id,
                    Code = _tourRepository.FindId(p.TourId).Code,
                    Name = _tourRepository.FindId(p.TourId).Name,
                    Partner = p.PartnerId != null ? _partnerRepository.FindId(p.PartnerId).Name : "",
                    Service = p.ServiceId != null ? _dictionaryRepository.FindId(p.ServiceId).Name : "",
                    NgayKhoiHanh = _tourRepository.FindId(p.TourId).StartDate != null ? _tourRepository.FindId(p.TourId).StartDate.Value.ToString("dd/MM/yyyy") : "",
                    NguoiDieuHanh = _tourRepository.FindId(p.TourId).StaffId != null ? _staffRepository.FindId(_tourRepository.FindId(p.TourId).StaffId).FullName : "",
                    Tag = _tourRepository.FindId(p.TourId).DestinationPlace != null ? _tagsRepository.FindId(_tourRepository.FindId(p.TourId).DestinationPlace).Tag : "",
                    TongGTDichVu = p.ServicePrice != null ? p.ServicePrice : 0,
                    TongGTConLai = p.TotalRemaining != null ? p.TotalRemaining : 0,
                    TongGTThanhToan = p.FirstPayment + p.SecondPayment,
                    Currency = _dictionaryRepository.FindId(p.FirstCurrencyType).Name
                }).ToList();
            return PartialView("_Partial_ListTourReport", model);
        }

        public ActionResult FilterTour(DateTime? start, DateTime? end, int? loai, int? vitri)
        {
            Permission(clsPermission.GetUser().PermissionID, 1118);

            var model = _liabilityPartnerRepository.GetAllAsQueryable().AsEnumerable()
                            .Where(p => (p.StaffId == maNV | maNV == 0)
                                & (p.tbl_Staff.DepartmentId == maPB | maPB == 0)
                                & (p.tbl_Staff.StaffGroupId == maNKD | maNKD == 0)
                                & (p.tbl_Staff.HeadquarterId == maCN | maCN == 0)

TRAVELPLUS/Views/LiabilitiesPartnerReport/Index.cshtml
@using CRM.Core
@using TRAVELPLUS.Utilities
@{
    ViewBag.Title = "Thống kê doanh thu - công nợ đối tác";
    int i = 0;
}

<div class="page-content">
    <!-- BEGIN PAGE HEAD-->
    <div class="page-head">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1>THỐNG KÊ DOANH THU - CÔNG NỢ ĐỐI TÁC</h1>
        </div>
        <!-- END PAGE TITLE -->

    </div>
    <!-- END PAGE HEAD-->
    <div class="note note-info">
        @using (Html.BeginForm("ExportExcel", "LiabilitiesPartnerReport", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="col-md-3">
                    <label>Kỳ báo cáo</label>
                    <select class="form-control" id="ddlKyBaoCao" style="width: 100%" name="kybaocao">
                        @foreach (var item in LoadData.KyBaoCaoList())
                        {
                            <option value="@i">@item</option>
                            i++;
                        }
                    </select>
                </div>
                <div id="startEndDate">
                    @{
                        DateTime dateFrom = DateTime.Now.AddYears(-2);
                        DateTime dateTo = new DateTime(DateTime.Now.Year, 12, 31);
                    }
                    <div class="col-md-3">
                        <label>Từ ngày</label>
                        <input type="date" id="txtStartDate" value="@dateFrom.ToString("yyyy-MM-dd")" class="form-control" name="tungay" required />
                    </div>
                    <div class="col-md-3">
                        <label>Đến ngày</label>
                        <input type="date" id="txtEndDate" value="@dateTo.ToString("yyyy-MM-dd")" class=" form-control" name="denngay" required />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Loại tour</label>
                    <select class="form-control" id="ddlLoaiTour" style="width: 100%" name="loai">
                        <option value="0">-- Tất cả --</option>
                        @foreach (var item in LoadData.TourTypeList())
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    </select>
                </div>
                <div class="col-md-3">
                    <label>Vị trí</label>
                    <select class="form-control" id="ddlViTri" style="width: 100%" name="vitri">
                        <option value="0">-- Tất cả --</option>
                        @foreach (var item in LoadData.DropdownlistLocation())
                        {
                            <option value="@item.Id">@item.Tags</option>
                        }
                    </select>
                </div>
                <div class="col-md-6" style="margin-top: 23px;">
                    <a class="btn btn-default" href="@Url.Action("Index", "LiabilitiesPartnerReport")"><i class="fa fa-refresh"></i>&nbsp;Refresh</a>
                    <button class="btn btn-success" type="button" id="btnSearch"><i class="fa fa-search"></i>&nbsp;Tìm</button>
                    <button class="btn btn-primary" type="submit" id="export"><i class="icon-action-undo"></i>&nbsp;Export</button>
                    <input type="hidden" id="listItemId" name="listItemId" />
                    <button type="button" class="btn btn-success" data-toggle="collapse" data-target="#demo"><i class="icon-book-open"></i>&nbsp;Ẩn/Hiện cột</button>
                </div>
            </div>
        }
    </div>
    <div class="row collapse" id="demo">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="portlet light bordered">
                <div class="portlet-body" id="data-customer">
                    <div class="row">
                        <div class="col-md-2 col-xs-2 col-sm-2">
                            <ul>
                                <li><a class="toggle-vis" data-column="1" style="color: #333; font-weight: bold">Code tour</a></li>
                                <li><a class="toggle-vis" data-column="2" style="color: #333; font-weight: bold">Tên tour</a></li>
                            </ul>
                        </div>
                        <div class="col-md-2 col-xs-2 col-sm-2">
                            <ul>
                                <li><a class="toggle-vis" data-column="3" style="color: #333; font-weight: bold">Điểm đến</a></li>
                                <li><a class="toggle-vis" data-column="4" style="color: #333; font-weight: bold">Tên đối tác</a></li>
                            </ul>
                        </div>
                        <div class="col-md-2 col-xs-2 col-sm-2">
                            <ul>
                                <li><a class="toggle-vis" data-column="5" style="color: #333; font-weight: bold">Dịch vụ</a></li>
                                <li><a class="toggle-vis" data-column="10" style="color: #333; font-weight: bold">Điều hành</a></li>
                            </ul>
                        </div>
                        <div class="col-md-3 col-xs-3 col-sm-3">
                            <ul>
                                <li><a class="toggle-vis" data-column="7" style="color: #333; font-weight: bold">Tổng GT dịch vụ</a></li>
                                <li><a class="toggle-vis" data-column="8" style="color: #333; font-weight: bold">Tổng GT thanh toán</a></li>
                            </ul>
                        </div>
                        <div class="col-md-3 col-xs-3 col-sm-3">
                            <ul>
                                <li><a class="toggle-vis" data-column="9" style="color: #333; font-weight: bold">Tổng GT còn lại</a></li>
                                <li><a class="toggle-vis" data-column="6" style="color: #333; font-weight: bold">Ngày khởi hành</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="portlet light bordered">
                <div class="portlet-body" id="data-tour">
                    @Html.Action("_Partial_ListTourReport", "LiabilitiesPartnerReport")
                </div>
            </div>
        </div>
    </div>
    <!-- END PAGE BASE CONTENT -->
</div>

@section scripts{
    <script src="~/Scripts/controller/reportlibpartner.js"></script>
}

TRAVELPLUS/Views/LiabilitiesPartnerReport/_Partial_ListTourReport.cshtml
@model IEnumerable<TRAVELPLUS.Models.LiabilitiesPartnerReportViewModel>
@{
    int i = 1;
}

<div class="table-scrollable table-custom-format" id="tableDictionary-Wrapper">
    <table class="table table-bordered table-hover dataTable" id="tableDictionary">
        <thead>
            <tr>
                <td class="width24"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th class="table-checkbox">
                    <input type="checkbox" id="allcb" name="allcb" onclick="SelectAllCb()" />
                </th>
                <th>Code tour</th>
                <th>Tên tour</th>
                <th>Điểm đến</th>
                <th>Tên đối tác</th>
                <th>Dịch vụ</th>
                <th>Ngày khởi hành</th>
                <th>Tổng GT dịch vụ</th>
                <th>Tổng GT thanh toán</th>
                <th>Tổng GT còn lại</th>
                <th>Điều hành</th>
            </tr>
        </thead>
        <tbody>

            @if (Model.Count() > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td class="width24">
                            <input type="checkbox" value="@item.Id" id="cb@(item.Id)" class="cbItem" name="cb" onclick="CheckSelect()" />
                        </td>
                        <td>@item.Code</td>
                        <td class="textalignleft">@item.Name</td>
                        <td class="textalignleft">@item.Tag</td>
                        <td class="textalignleft">@item.Partner</td>
                        <td class="textalignleft">@item.Service</td>
                        <td>@item.NgayKhoiHanh</td>
                        <td class="textalignright">@(item.TongGTDichVu == 0 ? "0" : string.Format("{0:0,0}", item.TongGTDichVu))</td>
                        <td class="textalignright">@(item.TongGTThanhToan == 0 ? "0" : string.Format("{0:0,0}", item.TongGTThanhToan))</td>
                        <td class="textalignright">@(item.TongGTConLai == 0 ? "0" : string.Format("{0:0,0}", item.TongGTConLai))</td>
                        <td>@item.NguoiDieuHanh</td>
                    </tr>
                    i++;
                }
            }

        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">Tổng cộng:</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td class="textalignright" style="padding-right: 5px">@string.Format("{0:0,0}", Model.Sum(p => p.TongGTDichVu))</td>
                <td class="textalignright" style="padding-right: 5px">@string.Format("{0:0,0}", Model.Sum(p => p.TongGTThanhToan))</td>
                <td class="textalignright" style="padding-right: 5px">@string.Format("{0:0,0}", Model.Sum(p => p.TongGTConLai))</td>
                <td></td>
            </tr>
        </tfoot>
    </table>
</div>