TRAVELPLUS/Controllers/Marketing/MailReceiveListController.cs
using CRM.Core;
using CRM.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TRAVELPLUS.Models;

namespace TRAVELPLUS.Controllers.Marketing
{
    public class MailReceiveListController : BaseController
    {
        // GET: MailReceiveList

        #region Init

        private IGenericRepository<tbl_Customer> _customerRepository;
        private IGenericRepository<tbl_MailReceiveList> _mailReceiveListRepository;
        private IGenericRepository<tbl_MailReceives> _mailReceivesRepository;
        private IGenericRepository<tbl_MailTemplates> _mailTemplatesRepository;
        private IGenericRepository<tbl_MailConfig> _mailConfigRepository;
        private IGenericRepository<tbl_MailImport> _mailImportRepository;
        private IGenericRepository<tbl_Staff> _staffRepository;
        private DataContext _db;

        public MailReceiveListController(
            IGenericRepository<tbl_Customer> customerRepository,
            IGenericRepository<tbl_MailReceiveList> mailReceiveListRepository,
            IGenericRepository<tbl_MailReceives> mailReceivesRepository,
            IGenericRepository<tbl_MailTemplates> mailTemplatesRepository,
            IGenericRepository<tbl_MailConfig> mailConfigRepository,
            IGenericRepository<tbl_Staff> staffRepository,
            IGenericRepository<tbl_MailImport> mailImportRepository,
            IBaseRepository baseRepository)
            : base(baseRepository)
            {
                this._customerRepository = customerRepository;
                this._mailReceiveListRepository = mailReceiveListRepository;
                this._mailReceivesRepository = mailReceivesRepository;
                this._mailTemplatesRepository = mailTemplatesRepository;
                this._mailConfigRepository = mailConfigRepository;
                this._staffRepository = staffRepository;
                this._mailImportRepository = mailImportRepository;
                _db = new DataContext();
            }
        #endregion

        #region Add Staff
        [HttpPost]
        public ActionResult AddStaff(int id)
        {
            Session["idReceive"] = id;
            var model = _staffRepository.GetAllAsQueryable().AsEnumerable().Where(p => p.IsDelete == false && p.IsVietlike == true).ToList();
            return PartialView("_Partial_StaffList", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> InsertStaff(FormCollection fc)
        {
            try
            {
                int idReceive = Int16.Parse(Session["idReceive"].ToString());
                if (fc["listItemIdAddStaff"] != null && fc["listItemIdAddStaff"] != "")
                {
                    var listIds = fc["listItemIdAddStaff"].Split(',');
                    listIds = listIds.Take(listIds.Count() - 1).ToArray();
                    if (listIds.Count() > 0)
                    {
                        foreach (var id in listIds)
                        {
                            int _id = Int16.Parse(id);
                            var item = _staffRepository.FindId(_id);
                            var staff = new tbl_MailReceiveList
                            {
                                Birthday = item.Birthday,
                                Department = item.DepartmentId != null ? item.tbl_DictionaryDepartment.Name : "",
                                Email = item.Email,
                                FullName = item.FullName,
                                HomeAddress = item.Address,
                                IsDelete = false,
                                MailReceiveId = idReceive,
                                Phone = item.Phone,
                                StaffId = item.Id,
                                Vocative = item.NameTypeId != null ? item.tbl_DictionaryNameType.Name : ""
                            };
                            await _mailReceiveListRepository.Create(staff);
                        }
                        return Json(new ActionModel() { Succeed = true, Code = "200", View = "", Message = "Lưu thành công !", IsPartialView = false, RedirectTo = Url.Action("Index", "MailReceive") }, JsonRequestBehavior.AllowGet);
                    }
                }
                return Json(new ActionModel() { Succeed = false, Code = "200", View = "", Message = "Vui lòng chọn người dùng !" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new ActionModel() { Succeed = false, Code = "200", View = "", Message = "Lưu không thành công !" }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Add Customer
        [HttpPost]
        public ActionResult AddCustomer(int id)
        {
            Session["idReceive"] = id;
            var model = _customerRepository.GetAllAsQueryable().AsEnumerable()
                .Where(p => p.IsDelete == false && p.IsTemp == false).OrderByDescending(p => p.CreatedDate).ToList();
            return PartialView("_Partial_CustomerList", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> InsertCustomer(FormCollection fc)
        {
            try
            {
                int idReceive = Int16.Parse(Session["idReceive"].ToString());
                if (fc["listItemIdAddCus"] != null && fc["listItemIdAddCus"] != "")
                {
                    var listIds = fc["listItemIdAddCus"].Split(',');
                    listIds = listIds.Take(listIds.Count() - 1).ToArray();
                    if (listIds.Count() > 0)
                    {
                        foreach (var id in listIds)
                        {
                            int _id = Int16.Parse(id);
                            var item = _customerRepository.FindId(_id);
                            var cus = new tbl_MailReceiveList
                            {
                                Birthday = item.Birthday,
                                Department = item.CareerId != null ? item.tbl_DictionaryCareer.Name : "",
                                Email = item.PersonalEmail,
                                FullName = item.FullName,
                                HomeAddress = item.Address,
                                IsDelete = false,
                                MailReceiveId = idReceive,
                                Phone = item.Phone,
                                CustomerId = item.Id,
                                Vocative = item.NameTypeId != null ? item.tbl_DictionaryNameType.Name : ""
                            };
                            await _mailReceiveListRepository.Create(cus);
                        }
                        return Json(new ActionModel() { Succeed = true, Code = "200", View = "", Message = "Lưu thành công !", IsPartialView = false, RedirectTo = Url.Action("Index", "MailReceive") }, JsonRequestBehavior.AllowGet);
                    }
                }
                return Json(new ActionModel() { Succeed = false, Code = "200", View = "", Message = "Vui lòng chọn người dùng !" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new ActionModel() { Succeed = false, Code = "200", View = "", Message = "Lưu không thành công !" }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Add Import
        [HttpPost]
        public ActionResult AddImport(int id)
        {
            Session["idReceive"] = id;
            var model = _mailImportRepository.GetAllAsQueryable().AsEnumerable()
                .Where(p => p.IsDelete == false).OrderByDescending(p => p.CreatedDate).ToList();
            return PartialView("_Partial_ImportList", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> InsertImport(FormCollection fc)
        {
            try
            {
                int idReceive = Int16.Parse(Session["idReceive"].ToString());
                if (fc["listItemIdAddImport"] != null && fc["listItemIdAddImport"] != "")
                {
                    var listIds = fc["listItemIdAddImport"].Split(',');
                    listIds = listIds.Take(listIds.Count() - 1).ToArray();
                    if (listIds.Count() > 0)
                    {
                        foreach (var id in listIds)
                        {
                            int _id = Int16.Parse(id);
                            var item = _mailImportRepository.FindId(_id);
                            var cus = new tbl_MailReceiveList
                            {
                                Email = item.Email,
                                FullName = item.Name,
                                IsDelete = false,
                                MailReceiveId = idReceive,
                                Phone = item.Phone,
                                MailImportId = item.Id,
                            };
                            await _mailReceiveListRepository.Create(cus);
                        }
                        return Json(new ActionModel() { Succeed = true, Code = "200", View = "", Message = "Lưu thành công !", IsPartialView = false, RedirectTo = Url.Action("Index", "MailReceive") }, JsonRequestBehavior.AllowGet);
                    }
                }
                return Json(new ActionModel() { Succeed = false, Code = "200", View = "", Message = "Vui lòng chọn người dùng !" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new ActionModel() { Succeed = false, Code = "200", View = "", Message = "Lưu không thành công !" }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion
    }
}

TRAVELPLUS/Views/MailReceiveList/_Partial_CustomerList.cshtml
@using CRM.Enum
@using CRM.Core
@using TRAVELPLUS.Models
@using TRAVELPLUS.Utilities
@model IEnumerable<tbl_Customer>
<div class="modal fade  bs-modal-lg" id="modal-add-customer" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Chọn khách hàng</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="table-scrollable table-custom-format">
                        <table class="table table-bordered table-hover dataTable3" id="tableCustomer">
                            <thead>
                                <tr>
                                    <th class="width24"></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                <tr>
                                    <th><input type="checkbox" id="allcustomer" name="allcustomer"/></th>
                                    <th>Xưng hô</th>
                                    <th>Họ tên</th>
                                    <th>Ngày sinh</th>
                                    <th>Điện thoại</th>
                                    <th>Địa chỉ</th>
                                    <th>Email</th>
                                    <th>Nghề nghiệp</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr class="odd gradeX">
                                            <td>
                                                <input type="checkbox" value="@item.Id" class="checkAddCustomer" name="checkAddCustomer" />
                                            </td>
                                            <td>@(item.NameTypeId != null ? item.tbl_DictionaryNameType.Name : "")</td>
                                            <td>@item.FullName</td>
                                            <td>@(item.Birthday != null ? item.Birthday.Value.ToString("dd/MM/yyyy") : "")</td>
                                            <td>@item.Phone</td>
                                            <td>@item.Address</td>
                                            <td>@item.PersonalEmail</td>
                                            <td>@(item.CareerId != null ? item.tbl_DictionaryCareer.Name : "")</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div align="center" style="margin-bottom: 20px">
                <form action="@Url.Action("InsertCustomer", "MailReceiveList")" method="post" id="formAddCustomer" style="position:absolute">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="listItemIdAddCus" name="listItemIdAddCus" value="" />
                </form>
                <button type="submit" class="btn blue" id="btnLuuAddCustomer">Lưu</button>
                <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>

<script>

</script>

TRAVELPLUS/Views/MailReceiveList/_Partial_ImportList.cshtml
@using CRM.Enum
@using CRM.Core
@using TRAVELPLUS.Models
@using TRAVELPLUS.Utilities
@model IEnumerable<tbl_MailImport>
<div class="modal fade  bs-modal-lg" id="modal-add-import" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Chọn danh sách email</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="table-scrollable table-custom-format">
                        <table class="table table-bordered table-hover dataTable4" id="tableImport">
                            <thead>
                                <tr>
                                    <th class="width24"></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                <tr>
                                    <th><input type="checkbox" id="allimport" name="allimport" /></th>
                                    <th>Họ tên</th>
                                    <th>Điện thoại</th>
                                    <th>Email</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr class="odd gradeX">
                                            <td>
                                                <input type="checkbox" value="@item.Id" class="checkAddImport" name="checkAddImport" />
                                            </td>
                                            <td>@item.Name</td>
                                            <td>@item.Phone</td>
                                            <td>@item.Email</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div align="center" style="margin-bottom: 20px">
                <form action="@Url.Action("InsertImport", "MailReceiveList")" method="post" id="formAddImport" style="position:absolute">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="listItemIdAddImport" name="listItemIdAddImport" value="" />
                </form>
                <button type="submit" class="btn blue" id="btnLuuAddImport">Lưu</button>
                <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>

TRAVELPLUS/Views/MailReceiveList/_Partial_StaffList.cshtml
@using CRM.Enum
@using CRM.Core
@using TRAVELPLUS.Models
@using TRAVELPLUS.Utilities
@model IEnumerable<tbl_Staff>
<div class="modal fade  bs-modal-lg" id="modal-add-staff" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Chọn nhân viên</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="table-scrollable table-custom-format">
                        <table class="table table-bordered table-hover dataTable2" id="tableStaff">
                            <thead>
                                <tr>
                                    <th class="width24"></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                <tr>
                                    <th><input type="checkbox" id="allstaff" name="allstaff" /></th>
                                    <th>Xưng hô</th>
                                    <th>Họ tên</th>
                                    <th>Ngày sinh</th>
                                    <th>Điện thoại</th>
                                    <th>Địa chỉ</th>
                                    <th>Email</th>
                                    <th>Phòng ban</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr class="odd gradeX">
                                            <td>
                                                <input type="checkbox" value="@item.Id" class="checkAddStaff" name="checkAddStaff" />
                                            </td>
                                            <td>@(item.NameTypeId != null ? item.tbl_DictionaryNameType.Name  : "")</td>
                                            <td>@item.FullName</td>
                                            <td>@(item.Birthday != null ? item.Birthday.Value.ToString("dd/MM/yyyy") : "")</td>
                                            <td>@item.Phone</td>
                                            <td>@item.Address</td>
                                            <td>@item.Email</td>
                                            <td>@(item.DepartmentId != null ? item.tbl_DictionaryDepartment.Name : "")</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div align="center" style="margin-bottom: 20px">
                <form action="@Url.Action("InsertStaff", "MailReceiveList")" method="post" id="formAddStaff" style="position:absolute">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="listItemIdAddStaff" name="listItemIdAddStaff" value="" />
                </form>
                <button type="submit" class="btn blue" id="btnLuuAddStaff">Lưu</button>
                <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>

<script>

</script>