TRAVELPLUS/Controllers/Program/ProgramsManageController.cs
using CRM.Core;
using CRM.Infrastructure;
using TRAVELPLUS.Models;
using TRAVELPLUS.Utilities;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace TRAVELPLUS.Controllers
{
    [Authorize]
    public class ProgramsManageController : BaseController
    {
        //
        // GET: /ProgramsManage/

        #region Init

        private IGenericRepository<tbl_Program> _programRepository;
        private IGenericRepository<tbl_Tags> _tagRepository;
        private IGenericRepository<tbl_Dictionary> _dictionaryRepository;
        private IGenericRepository<tbl_DocumentFile> _documentFileRepository;
        private IGenericRepository<tbl_Staff> _staffRepository;
        private IGenericRepository<tbl_Tour> _tourRepository;
        private IGenericRepository<tbl_UpdateHistory> _updateHistoryRepository;
        private DataContext _db;

        public ProgramsManageController(IGenericRepository<tbl_Dictionary> dictionaryRepository,
            IGenericRepository<tbl_Program> programRepository,
            IGenericRepository<tbl_DocumentFile> documentFileRepository,
            IGenericRepository<tbl_Tags> tagRepository,
            IGenericRepository<tbl_Staff> staffRepository,
            IGenericRepository<tbl_Tour> tourRepository,
            IGenericRepository<tbl_UpdateHistory> updateHistoryRepository,
            IBaseRepository baseRepository)
            : base(baseRepository)
        {
            this._tourRepository = tourRepository;
            this._programRepository = programRepository;
            this._documentFileRepository = documentFileRepository;
            this._dictionaryRepository = dictionaryRepository;
            this._tagRepository = tagRepository;
            this._staffRepository = staffRepository;
            this._updateHistoryRepository = updateHistoryRepository;
            _db = new DataContext();
        }

        #endregion

        #region Permisison
        int SDBID = 6;
        int maPB = 0, maNKD = 0, maNV = 0, maCN = 0;
        void Permission(int PermissionsId, int formId)
        {
            var list = _db.tbl_ActionData.Where(p => p.FormId == formId && p.PermissionsId == PermissionsId).Select(p => p.FunctionId).ToList();
            ViewBag.IsAdd = list.Contains(1);
            ViewBag.IsDelete = list.Contains(2);
            ViewBag.IsEdit = list.Contains(3);
            ViewBag.IsImport = list.Contains(4);
            ViewBag.IsExport = list.Contains(5);
            ViewBag.IsLock = list.Contains(6);
            ViewBag.IsUnLock = list.Contains(7);

            var ltAccess = _db.tbl_AccessData.Where(p => p.PermissionId == PermissionsId && p.FormId == formId).Select(p => p.ShowDataById).FirstOrDefault();
            if (ltAccess != 0)
                this.SDBID = ltAccess;

            switch (SDBID)
            {
                case 2: maPB = clsPermission.GetUser().DepartmentID;
                    maCN = clsPermission.GetUser().BranchID;
                    break;
                case 3: maNKD = clsPermission.GetUser().GroupID;
                    maCN = clsPermission.GetUser().BranchID; break;
                case 4: maNV = clsPermission.GetUser().StaffID; break;
                case 5: maCN = clsPermission.GetUser().BranchID; break;
            }
        }
        #endregion

        #region GetIdProgram
        [HttpPost]
        public ActionResult GetIdProgram(int id)
        {
            Session["idProgram"] = id;
            return Json(JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region List

        //[CheckSessionTimeOut]
        public ActionResult Index()
        {
            Permission(clsPermission.GetUser().PermissionID, 18);

            if (SDBID == 6)
                return View(new List<tbl_Program>());

            var model = _programRepository.GetAllAsQueryable()
                .Where(p => ((p.StaffId == maNV | maNV == 0)
                    || ((p.TourId != null) && (p.tbl_Tour.Permission != null && p.tbl_Tour.Permission.Contains(maNV.ToString())
                    || p.tbl_Tour.StaffId == maNV || p.tbl_Tour.CreateStaffId == maNV)))
                    & (p.tbl_Staff.DepartmentId == maPB | maPB == 0)
                    & (p.tbl_Staff.StaffGroupId == maNKD | maNKD == 0)
                    & (p.tbl_Staff.HeadquarterId == maCN | maCN == 0)
                    & (p.IsDelete == false)).OrderByDescending(p => p.CreatedDate).ToList();
            return View(model);
        }
        #endregion

        #region Create
        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(tbl_Program model, FormCollection form)
        {
            Permission(clsPermission.GetUser().PermissionID, 18);
            try
            {
                model.Code = GenerateCode.ProgramCode();
                model.CreatedDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;
                model.Permission = "";
                model.DictionaryId = 30;
                model.StaffId = clsPermission.GetUser().StaffID;
                if (model.TourId != null)
                {
                    var tour = _tourRepository.FindId(model.TourId);
                    model.CustomerId = tour.CustomerId;
                    model.TagsId = tour.DestinationPlace.ToString();
                    model.StartDate = tour.StartDate;
                    model.EndDate = tour.EndDate;
                    model.NumberDay = tour.NumberDay;
                }
                model.TotalPrice = 0;
                model.CurrencyId = 1209;

                if (await _programRepository.Create(model))
                {
                    UpdateHistory.SaveHistory(18, "Thêm mới chương trình, code: " + model.Code + " - " + model.Name,
                        null, //appointment
                        null, //contract
                        model.CustomerId, //customer
                        null, //partner
                        model.Id, //program
                        null, //task
                        model.TourId, //tour
                        null, //quotation
                        null, //document
                        null, //history
                        null // ticket
                        );
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            catch { }

            return RedirectToAction("Index");
        }
        #endregion

        #region Update

        [HttpPost]
        public ActionResult ProgramInfomation(int id)
        {
            var model = _db.tbl_Program.Find(id);
            if (clsPermission.GetUser().StaffID == 9 || model.DictionaryId <= 1147)
            {
                return PartialView("_Partial_EditProgram", model);
            }
            else
            {
                return Json(1, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Update(tbl_Program model, FormCollection form)
        {
            Permission(clsPermission.GetUser().PermissionID, 18);
            try
            {
                model.ModifiedDate = DateTime.Now;
                model.StaffId = clsPermission.GetUser().StaffID;
                if (model.TourId != null)
                {
                    var tour = _tourRepository.FindId(model.TourId);
                    model.CustomerId = tour.CustomerId;
                    model.TagsId = tour.DestinationPlace.ToString();
                    model.StartDate = tour.StartDate;
                    model.EndDate = tour.EndDate;
                    model.NumberDay = tour.NumberDay;
                }
                model.TotalPrice = 0;
                model.CurrencyId = 1209;
                if (await _programRepository.Update(model))
                {
                    UpdateHistory.SaveHistory(18, "Cập nhật chương trình: " + model.Code,
                        null, //appointment
                        null, //contract
                        model.CustomerId, //customer
                        null, //partner
                        model.Id, //program
                        null, //task
                        model.TourId, //tour
                        null, //quotation
                        null, //document
                        null, //history
                        null // ticket
                        );
                    return RedirectToAction("Index");
                }
            }
            catch { }

            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(FormCollection fc)
        {
            Permission(clsPermission.GetUser().PermissionID, 18);
            try
            {
                if (fc["listItemId"] != null && fc["listItemId"] != "")
                {
                    var listIds = fc["listItemId"].Split(',');
                    listIds = listIds.Take(listIds.Count() - 1).ToArray();
                    if (listIds.Count() > 0)
                    {
                        //
                        foreach (var i in listIds)
                        {
                            var item = _programRepository.FindId(Convert.ToInt32(i));
                            UpdateHistory.SaveHistory(18, "Xóa chương trình: " + item.Code + " - " + item.Name,
                                null, //appointment
                                null, //contract
                                item.CustomerId, //customer
                                null, //partner
                                item.Id, //program

TRAVELPLUS/Views/ProgramsManage/_Partial_EditDocument.cshtml
@using CRM.Core
@using TRAVELPLUS.Utilities
@model tbl_DocumentFile

<div class="modal fade " id="modal-edit-document" role="document" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Cập nhật tài liệu</h4>
            </div>
            @using (Ajax.BeginForm("UpdateDocument", "ProgramsManage", null, new AjaxOptions { OnFailure = "OnFailureAppointment", OnSuccess = "OnSuccessAppointment", UpdateTargetId = "tailieumau" }, new { id = "frmUpdateFile", enctype = "multipart/form-data" }))
            {
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Code</label>
                                    <div class="col-lg-9 col-md-9">
                                        @Html.TextBoxFor(model => model.Code, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">File</label>
                                    <div class="col-lg-9 col-md-9">
                                        @Html.HiddenFor(model => model.Id)
                                        @Html.HiddenFor(model => model.ProgramId)
                                        @Html.HiddenFor(model => model.CreatedDate)
                                        @Html.HiddenFor(model => model.PermissionStaff)
                                        @Html.HiddenFor(model => model.FileName)
                                        @Html.HiddenFor(model => model.FileSize)
                                        @Html.HiddenFor(model => model.StaffId)

                                        @Html.TextBoxFor(model => model.FileName, new { id = "edit-file", type = "file", @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Tags</label>
                                    <div class="col-lg-9 col-md-9">
                                        <select class="form-control" name="TagsId" id="edit-tag-document" style="width: 100%" multiple="multiple">
                                            @foreach (var item in LoadData.DropdownlistLocation())
                                            {
                                                <option value="@item.Id" @(Model.TagsId != null && Model.TagsId.Contains(item.Id.ToString()) ? "selected" : "")>@item.Tags</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Ghi chú</label>
                                    <div class="col-lg-9 col-md-9">
                                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control", id = "edit-document-note" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div align="center" style="margin-bottom: 20px">
                    <button type="submit" class="btn blue">Lưu</button>
                    <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

TRAVELPLUS/Views/ProgramsManage/_Partial_EditProgram.cshtml
@using TRAVELPLUS.Utilities
@using CRM.Core
@model tbl_Program

<div class="modal fade  bs-modal-lg" id="modal-edit-program" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Chương trình</h4>
            </div>
            @using (Html.BeginForm("Update", "ProgramsManage"))
            {
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.CreatedDate)
                @Html.HiddenFor(model => model.DictionaryId)
                @Html.HiddenFor(model => model.Permission)
                @Html.HiddenFor(model => model.StaffId)

                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Code</label>
                                    <div class="col-lg-4 col-md-4">
                                        @Html.TextBoxFor(model => model.Code, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                    <label class="control-label col-lg-2 col-md-2">Tour</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select class="form-control" id="edit-tour" name="TourId" style="width: 100%">
                                            <option>-- Chọn tour --</option>
                                            @foreach (var item in LoadData.TourList())
                                            {
                                                <option value="@item.Id" @(Model != null && Model.TourId == item.Id ? "selected" : "")>[@item.Code] @item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Trạng thái</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select class="form-control" id="edit-status" name="StatusId" style="width: 100%">
                                            @foreach (var item in LoadData.StatusProcessList())
                                            {
                                                <option value="@item.Id" @(Model.StatusId != null && Model.StatusId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Tên chương trình</label>
                                    <div class="col-lg-10 col-md-10">
                                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control",  })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Ghi chú</label>
                                    <div class="col-lg-10 col-md-10">
                                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control", id = "edit-note" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div align="center" style="margin-bottom: 20px">
                    <button type="submit" class="btn blue">Lưu</button>
                    <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

TRAVELPLUS/Views/ProgramsManage/_Partial_InsertProgram.cshtml
@using TRAVELPLUS.Utilities
@using CRM.Core
@model tbl_Program

<div class="modal fade  bs-modal-lg" id="modal-insert-program" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Chương trình</h4>
            </div>
            @using (Html.BeginForm("Create", "ProgramsManage"))
            {
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Code</label>
                                    <div class="col-lg-4 col-md-4">
                                        <input type="text" name="Code" id="Code" value="@GenerateCode.ProgramCode()" class="form-control"  readonly="readonly" />
                                    </div>
                                    <label class="control-label col-lg-2 col-md-2">Tour</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select class="form-control" id="insert-tour" name="TourId" style="width: 100%">
                                            <option>-- Chọn tour --</option>
                                            @foreach (var item in LoadData.TourList())
                                            {
                                                <option value="@item.Id">[@item.Code] @item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Trạng thái</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select class="form-control" id="insert-status" name="StatusId" style="width: 100%">
                                            @foreach (var item in LoadData.StatusProcessList())
                                            {
                                                <option value="@item.Id">@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Tên chương trình</label>
                                    <div class="col-lg-10 col-md-10">
                                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control",  })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Ghi chú</label>
                                    <div class="col-lg-10 col-md-10">
                                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control", id = "insert-note" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div align="center" style="margin-bottom: 20px">
                    <button type="submit" class="btn blue">Lưu</button>
                    <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

TRAVELPLUS/Views/ProgramsManage/_Partial_SupportProgram.cshtml
<div class="modal fade  bs-modal-lg" id="modal-support-contract" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Chọn nhân viên hỗ trợ</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="table-scrollable table-custom-format">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Mã số</th>
                                    <th>Họ tên</th>
                                    <th>Ngày sinh</th>
                                    <th>Địa chỉ</th>
                                    <th>Phòng ban</th>
                                    <th>Chức vụ</th>
                                    <th>Nhóm</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="">
                                    <td></td>
                                    <td>
                                        <input type="text" class="form-control" /></td>
                                    <td>
                                        <input type="text" class="form-control" /></td>
                                    <td>
                                        <input type="text" class="form-control" /></td>
                                    <td>
                                        <input type="text" class="form-control" /></td>
                                    <td>
                                        <input type="text" class="form-control" /></td>
                                    <td>
                                        <input type="text" class="form-control" /></td>
                                    <td>
                                        <input type="text" class="form-control" /></td>
                                </tr>
                                @for (int i = 0; i < 5; i++)
                                {
                                    <tr class="odd gradeX">
                                        <td>
                                            <input type="checkbox" name="checkAddUser" /></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div align="center" style="margin-bottom: 20px">
                <button type="button" class="btn blue" id="btnLuuAddUser">Lưu</button>
                <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>

TRAVELPLUS/Views/ProgramsManage/_Partial_WorkProgram.cshtml
@using TRAVELPLUS.Utilities
@using CRM.Core
@model tbl_UpdateHistory

<div class="modal fade" id="modal-work-contract" role="document" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Nhật ký xử lý</h4>
            </div>
            @using (Html.BeginForm("UpdateStatus", "ProgramsManage"))
            {
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Tình trạng</label>
                                    <div class="col-lg-9 col-md-9">
                                        <select class="form-control" name="DictionaryId" id="status-work" style="width: 100%">
                                            @foreach (var item in LoadData.StatusProcessList())
                                            {
                                                <option value="@item.Id">@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div align="center" style="margin-bottom: 20px">
                                <button type="submit" class="btn blue" id="btnThucHien">Thực hiện</button>
                                <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>