TRAVELPLUS/Controllers/Tour/TourBiddingManageController.cs
using CRM.Core;
using CRM.Enum;
using CRM.Infrastructure;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TRAVELPLUS.Models;
using TRAVELPLUS.Utilities;

namespace TRAVELPLUS.Controllers.Tour
{
    public class TourBiddingManageController : BaseController
    {
        //
        // GET: /TourManage/

        #region Init

        private IGenericRepository<tbl_Dictionary> _dictionaryRepository;
        private IGenericRepository<tbl_ServicesPartner> _servicesPartnerRepository;
        private IGenericRepository<tbl_Tour> _tourRepository;
        private IGenericRepository<tbl_ReviewTour> _reviewTourRepository;
        private IGenericRepository<tbl_ReviewTourDetail> _reviewTourDetailRepository;
        private IGenericRepository<tbl_Customer> _customerRepository;
        private IGenericRepository<tbl_CustomerVisa> _customerVisaRepository;
        private IGenericRepository<tbl_Tags> _tagsRepository;
        private IGenericRepository<tbl_Task> _taskRepository;
        private IGenericRepository<tbl_TaskStaff> _taskStaffRepository;
        private IGenericRepository<tbl_DocumentFile> _documentFileRepository;
        private IGenericRepository<tbl_AppointmentHistory> _appointmentHistoryRepository;
        private IGenericRepository<tbl_ContactHistory> _contactHistoryRepository;
        private IGenericRepository<tbl_Contract> _contractRepository;
        private IGenericRepository<tbl_Partner> _partnerRepository;
        private IGenericRepository<tbl_TourGuide> _tourGuideRepository;
        private IGenericRepository<tbl_TourSchedule> _tourScheduleRepository;
        private IGenericRepository<tbl_TourCustomer> _tourCustomerRepository;
        private IGenericRepository<tbl_TourCustomerVisa> _tourCustomerVisaRepository;
        private IGenericRepository<tbl_TourOption> _tourOptionRepository;
        private IGenericRepository<tbl_Staff> _staffRepository;
        private IGenericRepository<tbl_LiabilityCustomer> _liabilityCustomerRepository;
        private IGenericRepository<tbl_LiabilityPartner> _liabilityPartnerRepository;
        private IGenericRepository<tbl_CustomerContact> _customerContactRepository;
        private IGenericRepository<tbl_CustomerContactVisa> _customerContactVisaRepository;
        private IGenericRepository<tbl_UpdateHistory> _updateHistoryRepository;
        private DataContext _db;

        public TourBiddingManageController(IGenericRepository<tbl_Dictionary> dictionaryRepository,
            IGenericRepository<tbl_TaskStaff> taskStaffRepository,
            IGenericRepository<tbl_ServicesPartner> servicesPartnerRepository,
            IGenericRepository<tbl_Tour> tourRepository,
            IGenericRepository<tbl_ReviewTour> reviewTourRepository,
            IGenericRepository<tbl_ReviewTourDetail> reviewTourDetailRepository,
            IGenericRepository<tbl_Customer> customerRepository,
            IGenericRepository<tbl_CustomerVisa> customerVisaRepository,
            IGenericRepository<tbl_Tags> tagsRepository,
            IGenericRepository<tbl_Task> taskRepository,
            IGenericRepository<tbl_DocumentFile> documentFileRepository,
            IGenericRepository<tbl_AppointmentHistory> appointmentHistoryRepository,
            IGenericRepository<tbl_ContactHistory> contactHistoryRepository,
            IGenericRepository<tbl_Contract> contractRepository,
            IGenericRepository<tbl_Partner> partnerRepository,
            IGenericRepository<tbl_TourGuide> tourGuideRepository,
            IGenericRepository<tbl_TourSchedule> tourScheduleRepository,
            IGenericRepository<tbl_TourCustomer> tourCustomerRepository,
            IGenericRepository<tbl_TourCustomerVisa> tourCustomerVisaRepository,
            IGenericRepository<tbl_TourOption> tourOptionRepository,
            IGenericRepository<tbl_Staff> staffRepository,
            IGenericRepository<tbl_LiabilityCustomer> liabilityCustomerRepository,
            IGenericRepository<tbl_LiabilityPartner> liabilityPartnerRepository,
            IGenericRepository<tbl_CustomerContact> customerContactRepository,
            IGenericRepository<tbl_CustomerContactVisa> customerContactVisaRepository,
            IGenericRepository<tbl_UpdateHistory> updateHistoryRepository,
            IBaseRepository baseRepository)
            : base(baseRepository)
        {
            this._dictionaryRepository = dictionaryRepository;
            this._servicesPartnerRepository = servicesPartnerRepository;
            this._tourRepository = tourRepository;
            this._reviewTourRepository = reviewTourRepository;
            this._reviewTourDetailRepository = reviewTourDetailRepository;
            this._customerRepository = customerRepository;
            this._customerVisaRepository = customerVisaRepository;
            this._tagsRepository = tagsRepository;
            this._taskRepository = taskRepository;
            this._documentFileRepository = documentFileRepository;
            this._appointmentHistoryRepository = appointmentHistoryRepository;
            this._contactHistoryRepository = contactHistoryRepository;
            this._contractRepository = contractRepository;
            this._partnerRepository = partnerRepository;
            this._tourGuideRepository = tourGuideRepository;
            this._tourScheduleRepository = tourScheduleRepository;
            this._tourCustomerRepository = tourCustomerRepository;
            this._tourCustomerVisaRepository = tourCustomerVisaRepository;
            this._tourOptionRepository = tourOptionRepository;
            this._staffRepository = staffRepository;
            this._liabilityCustomerRepository = liabilityCustomerRepository;
            this._liabilityPartnerRepository = liabilityPartnerRepository;
            this._taskStaffRepository = taskStaffRepository;
            this._customerContactRepository = customerContactRepository;
            this._customerContactVisaRepository = customerContactVisaRepository;
            this._updateHistoryRepository = updateHistoryRepository;
            _db = new DataContext();
        }

        #endregion

        #region List

        [HttpPost]
        public ActionResult GetIdTour(int id)
        {
            Session["idTour"] = id;
            return Json(JsonRequestBehavior.AllowGet);
        }


        //[CheckSessionTimeOut]
        public ActionResult Index()
        {
            // phân quyền
            Permission(clsPermission.GetUser().PermissionID, 24);
            return View();
        }

        int SDBID = 6;
        void Permission(int PermissionsId, int formId)
        {
            var list = _db.tbl_ActionData.Where(p => p.FormId == formId & p.PermissionsId == PermissionsId).Select(p => p.FunctionId).ToList();
            ViewBag.IsAdd = list.Contains(1);
            ViewBag.IsEdit = list.Contains(3);
            ViewBag.IsDelete = list.Contains(2);

            //cập nhật trạng thái
            var listUS = _db.tbl_ActionData.Where(p => p.FormId == 24 & p.PermissionsId == PermissionsId).Select(p => p.FunctionId).ToList();
            ViewBag.IsUpdateStatus = list.Contains(1);

            //phân công nhiệm vụ
            var listNV = _db.tbl_ActionData.Where(p => p.FormId == 78 & p.PermissionsId == PermissionsId).Select(p => p.FunctionId).ToList();
            ViewBag.IsAddNV = list.Contains(1);

            //tạo lịch đi tour
            var listLDT = _db.tbl_ActionData.Where(p => p.FormId == 91 & p.PermissionsId == PermissionsId).Select(p => p.FunctionId).ToList();
            ViewBag.IsAddLDT = listLDT.Contains(1);

            var ltAccess = _db.tbl_AccessData.Where(p => p.PermissionId == PermissionsId & p.FormId == formId).Select(p => p.ShowDataById).FirstOrDefault();
            if (ltAccess != 0)
                this.SDBID = ltAccess;
        }

        public ActionResult _Partial_ListTours()
        {
            Permission(clsPermission.GetUser().PermissionID, 24);
            if (SDBID == 7)
                return PartialView("_Partial_ListTours", new List<TourListViewModel>());

            try
            {
                int maPB = 0, maNKD = 0, maNV = 0, maCN = 0;
                switch (SDBID)
                {
                    case 2:
                        maPB = clsPermission.GetUser().DepartmentID;
                        maCN = clsPermission.GetUser().BranchID;
                        break;
                    case 3:
                        maNKD = clsPermission.GetUser().GroupID;
                        maCN = clsPermission.GetUser().BranchID; break;
                    case 4: maNV = clsPermission.GetUser().StaffID; break;
                    case 5: maCN = clsPermission.GetUser().BranchID; break;
                }

                var model = _tourRepository.GetAllAsQueryable().Where(p =>
                    ((p.tbl_TourGuide.FirstOrDefault(g => g.StaffId == maNV) != null)
                    || (p.Permission.Contains(maNV.ToString()))
                    || (p.StaffId == maNV | maNV == 0))
                    || (p.CreateStaffId == maNV | maNV == 0)
                    & (p.tbl_StaffCreate.DepartmentId == maPB | maPB == 0)
                    & (p.tbl_StaffCreate.StaffGroupId == maNKD | maNKD == 0)
                    & (p.tbl_StaffCreate.HeadquarterId == maCN | maCN == 0) & (p.IsDelete == false))
                    .OrderByDescending(p => p.CreatedDate)
                    .Where(x => x.IsBidding == true)
                    .Select(p => new TourListViewModel
                    {
                        Id = p.Id,
                        Code = p.Code,
                        Name = p.Name,
                        CustomerName = p.tbl_Customer.FullName,
                        NumberCustomer = p.NumberCustomer ?? 0,
                        DestinationPlace = p.tbl_TagsDestinationPlace.Tag,

TRAVELPLUS/Views/TourBiddingManage/_Partial_EditCustomerNote.cshtml
@using TRAVELPLUS.Utilities
@using CRM.Core
@model tbl_Customer

<div class="modal fade bs-modal-lg" id="modal-update-note" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        @using (Ajax.BeginForm("UpdateCustomerNote", "TourBiddingManage", null, new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "OnSuccess", UpdateTargetId = "khachhang" }))
        {
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.StaffId)
            <input type="hidden" id="listVisaId" name="listVisaId" />
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Cập nhật Ghi chú</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Ghi chú</label>
                                    <div class="col-lg-10 col-md-10">
                                        @*<textarea name="NoteTour" class="form-control" id="edit-note-visa"></textarea>*@
                                        @Html.TextAreaFor(model => model.NoteTour, new { @class = "form-control", id = "edit-note-tour" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div align="center" style="margin-bottom: 20px">
                    <button type="submit" class="btn blue" id="btnLuuThem">Lưu</button>
                    <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                </div>
            </div>
        }
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

TRAVELPLUS/Views/TourBiddingManage/_Partial_EditTour.cshtml
@using CRM.Core
@using TRAVELPLUS.Utilities
@model TRAVELPLUS.Models.TourViewModel
@{
    var tourguide = ViewBag.ListTourGuide as List<tbl_TourGuide>;
}

<div class="modal fade bs-modal-lg" id="modal-edit-tour" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Cập nhật tour mới</h4>
            </div>
            @using (Html.BeginForm("Update", "TourBiddingManage", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(model => model.SingleTour.Id)
                @Html.HiddenFor(model => model.SingleTour.CreatedDate)
                @Html.HiddenFor(model => model.SingleTour.CreateStaffId)

                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Tên tour</label>
                                    <div class="col-lg-10 col-md-10">
                                        @Html.TextBoxFor(model => model.SingleTour.Name, new { @class = "form-control", })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Code tour</label>
                                    <div class="col-lg-8 col-md-8">
                                        @Html.TextBoxFor(model => model.SingleTour.Code, new { @readonly = "readonly", @class = "form-control", required = "required" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Ngày khởi hành</label>
                                    <div class="col-lg-8 col-md-8">
                                        @Html.TextBoxFor(model => model.StartDateTour, "{0:yyyy-MM-dd}", new { type = "date", @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Ngày về</label>
                                    <div class="col-lg-8 col-md-8">
                                        @Html.TextBoxFor(model => model.EndDateTour, "{0:yyyy-MM-dd}", new { type = "date", @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Khách hàng</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select class="form-control" id="edit-customer-tour" style="width: 100%" name="SingleTour.CustomerId">
                                            <option>-- Chọn khách hàng --</option>
                                            @foreach (var item in LoadData.CustomerList())
                                            {
                                                <option value="@item.Id" @( Model.SingleTour != null && Model.SingleTour.CustomerId == item.Id ? "selected" : "")>@item.FullName</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Số ngày</label>
                                    <div class="col-lg-8 col-md-8">
                                        @Html.TextBoxFor(model => model.SingleTour.NumberDay, new { @class = "form-control", type = "number", min = "0" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Nơi đi</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select class="form-control" id="edit-start-place" style="width: 100%" name="SingleTour.StartPlace">
                                            @foreach (var item in LoadData.TinhThanhQuocGia())
                                            {
                                                <option value="@item.Id" @(Model.SingleTour != null && Model.SingleTour.StartPlace == item.Id ? "selected" : "")>@item.Tags</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Nơi đến</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select class="form-control" id="edit-destination-place" style="width: 100%" name="SingleTour.DestinationPlace">
                                            @foreach (var item in LoadData.TinhThanhQuocGia())
                                            {
                                                <option value="@item.Id" @(Model.SingleTour != null && Model.SingleTour.DestinationPlace == item.Id ? "selected" : "")>@item.Tags</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Loại tour</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select class="form-control" id="edit-type-tour" style="width: 100%" name="SingleTour.TypeTourId">
                                            @foreach (var item in LoadData.TourTypeList())
                                            {
                                                <option value="@item.Id" @(Model.SingleTour != null && Model.SingleTour.TypeTourId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Điều hành</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select name="SingleTour.StaffId" id="edit-manager-tour" class="form-control" style="width: 100%">
                                            @foreach (var item in LoadData.StaffList())
                                            {
                                                <option value="@item.Id" @(Model.SingleTour != null && Model.SingleTour.StaffId == item.Id ? "selected" : "")>[@item.Code] @item.FullName</option>
                                            }
                                        </select>
                                    </div>
                                    <label class="control-label col-lg-2 col-md-2">Số lượng khách</label>
                                    <div class="col-lg-4 col-md-4">
                                        @Html.TextBoxFor(model => model.SingleTour.NumberCustomer, new { type = "number", @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Tình trạng</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select name="SingleTour.StatusId" id="edit-status-tour" class="form-control" style="width: 100%">
                                            @foreach (var item in LoadData.StatusTourList())
                                            {
                                                <option value="@item.Id" @(Model.SingleTour.StatusId != null && Model.SingleTour.StatusId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Phân quyền</label>
                                    <div class="col-lg-10 col-md-10">
                                        <select class="form-control" multiple="multiple" id="edit-permission-tour" style="width: 100%" name="SingleTour.Permission">
                                            @foreach (var item in LoadData.StaffList())
                                            {
                                                <option value="@item.Id" @(Model.SingleTour != null && Model.SingleTour.Permission != null && Model.SingleTour.Permission.Split(',').Contains(item.Id.ToString()) ? "selected" : "")>[@item.Code] @item.FullName</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Chi tiết chuyến bay</label>
                                    <div class="col-lg-10 col-md-10">
                                        @Html.TextAreaFor(model => model.SingleTour.NoteFlight, new { @class = "form-control", id = "edit-noteflight-tour" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Ghi chú</label>
                                    <div class="col-lg-10 col-md-10">
                                        @Html.TextAreaFor(model => model.SingleTour.Request, new { @class = "form-control", id = "edit-note-tour" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Thời gian gửi thầu</label>
                                    <div class="col-lg-8 col-md-8">
                                        @Html.TextBoxFor(model => model.SingleTour.BiddingDate, new { type = "date", @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Ngày thông báo kết quả thầu</label>
                                    <div class="col-lg-8 col-md-8">
                                        @Html.TextBoxFor(model => model.SingleTour.BiddingResultDate, new { type = "date", @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div align="center" style="margin-bottom: 20px">
                    <button type="submit" class="btn blue">Lưu</button>
                    <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

TRAVELPLUS/Views/TourBiddingManage/_Partial_UpdateStatus.cshtml
@using TRAVELPLUS.Utilities
@using CRM.Core
@model tbl_Tour

<div class="modal fade bs-modal-lg" id="modal-update-status" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Cập nhật tình trạng</h4>
            </div>
            @using (Ajax.BeginForm("UpdateStatusTour", "TourBiddingManage", null, new AjaxOptions { OnFailure = "OnFailureTour", OnSuccess = "OnSuccessTour", UpdateTargetId = "data-tour" }))
            {
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Tình trạng</label>
                                    <div class="col-lg-7 col-md-7">
                                        @Html.HiddenFor(model => model.Id) @Html.HiddenFor(model => model.NoteFlight)
                                        @Html.HiddenFor(model => model.Code) @Html.HiddenFor(model => model.NumberCustomer)
                                        @Html.HiddenFor(model => model.ContactId) @Html.HiddenFor(model => model.NumberDay)
                                        @Html.HiddenFor(model => model.CreatedDate) @Html.HiddenFor(model => model.Permission)
                                        @Html.HiddenFor(model => model.CreateStaffId) @Html.HiddenFor(model => model.Request)
                                        @Html.HiddenFor(model => model.CustomerId) @Html.HiddenFor(model => model.StaffId)
                                        @Html.HiddenFor(model => model.DestinationPlace) @Html.HiddenFor(model => model.StartDate)
                                        @Html.HiddenFor(model => model.EndDate) @Html.HiddenFor(model => model.StartPlace)
                                        @Html.HiddenFor(model => model.IsDelete) @Html.HiddenFor(model => model.TypeTourId)
                                        @Html.HiddenFor(model => model.IsUpdate) @Html.HiddenFor(model => model.Name)
                                        <select class="form-control" name="StatusId" id="update-status" style="width: 100%">
                                            @foreach (var item in LoadData.StatusTourList())
                                            {
                                                <option value="@item.Id" @(Model.StatusId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div align="center" style="margin-bottom: 20px">
                    <button type="submit" class="btn blue" id="btnLuuThem">Lưu</button>
                    <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

TRAVELPLUS/Views/TourBiddingManage/_Partial_Update_TourType.cshtml
@using TRAVELPLUS.Utilities

<div class="modal fade  bs-modal-lg" id="modal-update-tourtype" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Chuyển đổi loại tour</h4>
            </div>
            @using (Html.BeginForm("UpdateTypeTour", "TourBiddingManage"))
            { 
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label col-lg-4 col-md-4">Loại tour</label>
                                <div class="col-lg-6 col-md-6">
                                    <select class="form-control" name="TourTypeId" id="update-type-tour" style="width: 100%">
                                        @foreach (var item in LoadData.TourTypeList())
                                        {
                                            <option value="@item.Id">@item.Name</option>
                                        }
                                        <option value="99999">Thầu</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div align="center" style="margin-bottom: 20px">
                <button type="submit" class="btn blue">Lưu</button>
                <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
            </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>